// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"github.com/bangumi/server/internal/model"
)

const TableNameEpRevision = "chii_ep_revisions"

// EpRevision mapped from table <chii_ep_revisions>
type EpRevision struct {
	ID          uint32          `gorm:"column:ep_rev_id;type:mediumint(8) unsigned;primaryKey;autoIncrement:true"`
	Sid         model.SubjectID `gorm:"column:rev_sid;type:mediumint(8) unsigned;not null"`
	Eids        string          `gorm:"column:rev_eids;type:varchar(255);not null"`
	EpInfobox   string          `gorm:"column:rev_ep_infobox;type:mediumtext;not null"`
	CreatorID   uint32          `gorm:"column:rev_creator;type:mediumint(8) unsigned;not null"`
	Version     bool            `gorm:"column:rev_version;type:tinyint(1) unsigned;not null"`
	CreatedTime uint32          `gorm:"column:rev_dateline;type:int(10) unsigned;not null"`
	EditSummary string          `gorm:"column:rev_edit_summary;type:varchar(200);not null"`
}

// TableName EpRevision's table name
func (*EpRevision) TableName() string {
	return TableNameEpRevision
}
